name: deploy

on:
  push:
    branches: [ "prod" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secrets
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "ALGORITHM=${{ secrets.ALGORITHM }}" >> .env
          echo "ACCESS_TOKEN_EXPIRE_HOURS=${{ secrets.ACCESS_TOKEN_EXPIRE_HOURS }}" >> .env
      
      - name: Build auth image
        run: docker-compose build

      - name: Stop and remove old containers
        run: |
          docker-compose down

      - name: Deploy new microservice
        run: docker-compose up -d

      - name: Clean up unused images
        run: docker image prune -f

      - name: Verify deployment
        run: |
          echo "=== Deployment Status ==="
          docker ps --filter "name=auth_service"